language: node_js

node_js:
    - "0.10"
    - "0.12"
    - "4"
    - "6"

after_success:
  - |
      if [ "${TRAVIS_NODE_VERSION}" == "4" ]; then
        npm i coveralls
        npm run coverage
      fi
