language: node_js

node_js:
    - "0.10"
    - "0.11"

script: npm run travis

after_success:
  - |
      if [ "${TRAVIS_NODE_VERSION}" == "0.10" ]; then
        npm i istanbul istanbul-coveralls
        istanbul cover --report lcovonly ./node_modules/.bin/_mocha
        istanbul-coveralls && echo "Coverage data was sent to coveralls!"
      fi
